### ISSUE TITLE
Crash from Core::EventCreator::castable()

### ISSUE THREAD

**Issue by tigrangs** [hop-/Mercurius#5]
Crash occur after randomly key presses
#0  0x0000000000417e45 in Core::EventCreatorCore::KeyEvent::castable (e=0x7b67a0) at /home/tigrangs/Git/Mercurius/src/core/event.hpp:25
#1  0x0000000000417d93 in Core::EventCreatorCore::KeyEvent::cast (e=0x7b67a0) at /home/tigrangs/Git/Mercurius/src/core/event.hpp:30
#2  0x0000000000417881 in Assets::RunningLeft::process (this=0xbe2910, e=0x7b67a0) at src/assets/states.cpp:39
#3  0x000000000041cefc in Core::LogicObject::process (this=0xbfb420, event=0x7b67a0) at src/core/logic_object.cpp:53
#4  0x0000000000418086 in Core::Logic::update (this=0x664a30) at src/core/logic.cpp:19
#5  0x00000000004255e5 in Core::Layer::update (this=0x664b90) at src/core/layer.cpp:51
#6  0x000000000042a98c in Core::Game::mainLoop (this=0x661fc0) at src/core/game.cpp:100
#7  0x000000000042ab20 in Core::Game::start (this=0x661fc0) at src/core/game.cpp:127
#8  0x0000000000410345 in Assets::Mercurius::start () at src/assets/mercurius.cpp:24
#9  0x000000000042f201 in main (argc=1, argv=0x7fffffffdfe8) at src/main.cpp:11

**Comment by tigrangs** [comment]
after today's check-ins it is not possible to reproduce looks like fixed so I am closing this bug

**Comment by tigrangs** [comment]
sometimes game crashes, look like the same bug
